### PR TITLE
Weighted-Jacobi on C-relaxation

### PR DESCRIPTION
**Pull request by masumis**
I have added the weighted-Jacobi on C-relaxation.

I have created
- an example of 1D heat equation with non-unitary weight (example2_heat_1d.py)
- an example of advection equation with non-unitary weight (example2_advection.py)

### CODE REVIEW

**Comment by jbschroder** [comment]
@sfriedhoff @JensHahne @masumis

Hi Stephanie, Jens:  Hope all is well!  

Masumi has integrated a weighted-Jacobi relaxation into your code, and we wanted your opinion on it.  It looks correct to us, as far as we can tell.  Let us know what you think!

- Jacob

**Comment by JensHahne** [comment]
@masumis @jbschroder 

That looks very good. Thank you very much for the integration and use of PyMGRIT

One suggestion: We should probably outsource the multiplication to the vector class. This would give us another necessary function in the vector classes, but we would avoid the function get_values in the MGRIT class. The idea of get_values is to be a getter for the step function that can return multiple variables in other examples. This would not work at the moment. Outsourcing the multiplication to the vector class would solve this problem, and the MGRIT class is independent of the function get_values.

In the end we could end up with something like this (not tested):

In the MGRIT class:
self.u[lvl][i] = self.u[lvl][i] * omega + uOld[lvl][i] * (1.0 - omega)

In the heat_1d vector class:
def __mul__(self, other):
    tmp = VectorHeat1D(self.size)
    tmp.set_values(self.get_values() * other)
    return tmp

**Comment by JensHahne** [comment]
@masumis 

I merged your changes into a new branch and moved the multiplication to the vector class. Short tests show the same results for your examples. Please run your tests again and check the results

If everything works as expected, I would add the multiplication to the other vector classes and update the tests and documentation. 

Thank you :)

**Comment by sfriedhoff** [comment]
@masumis @jbschroder @JensHahne 

Hi Masumi, hi Jacob,

Thanks for your contribution to PyMGRIT and sorry for my slow reply. I was on vacation last week (while this was still possible and before teaching will start in less than two weeks). 

Since tests look good, we will merge the weighted C-relaxation into the master branch very soon.

Best,
Stephanie

**Comment by masumis** [comment]
@sfriedhoff @JensHahne @jbschroder

I am very sorry for the late reply.
I ran my tests (1D heat equation and advection equation) again, and they produced the same results. Thank you for pulling in my code. I am happy to be able to contribute to this project.

Thank you very much,

Masumi

**Pull request merged**
